import { useMemo, useState, type CSSProperties } from 'react'
import { Avatar } from '../../components/Avatar'
import { Icon } from '../../components/Icon'
import { MemberProfileDrawer } from '../../components/MemberProfileDrawer'
import { ContextMenu, useContextMenu, type ContextAction } from '../../components/ContextMenu'
import { useAppDialog } from '../../components/AppDialog'
import { useSpaces } from '../../state/SpacesContext'
import { usePreferences } from '../../state/PreferencesContext'
import { useBlockedUserIds } from '../../hooks/useBlockedUsers'
import { blockUser, unblockUser } from '../../api/social-api'
import { hasWorkspacePermission, platformRoleLabel } from '../../utils/permissions'
import { workspaceRoleDisplayName } from '../../utils/workspace-local-meta'
import { dispatchSupportIntakeV77 } from '../support/v77/support-v77-api'

export function MembersView() {
  const dialog = useAppDialog()
  const menu = useContextMenu()
  const { apiUrl, data, profile, session, setMemberRoles, removeMember, requestDirectConversation, getDirectCenter, reportUser, pushToast } = useSpaces()
  const { effectivePresence, preferences } = usePreferences()
  const blockedUserIds = useBlockedUserIds(session?.token)
  const [selectedId, setSelectedId] = useState('')
  const [query, setQuery] = useState('')
  const [roleBusyId, setRoleBusyId] = useState('')
  const memberMenuV77 = useContextMenu()
  const members = data?.members ?? []
  const roles = useMemo(() => [...(data?.roles ?? [])].sort((a, b) => b.position - a.position), [data?.roles])
  const currentMember = members.find(member => member.profileId === profile?.id)
  const isHubFounder = data?.workspace.id === 'spaces-hub' && profile?.platformRole === 'founder'
  const actorIsOwner = Boolean(isHubFounder || currentMember?.role === 'owner' || data?.workspace.ownerId === profile?.id)
  const canManageRoles = isHubFounder || hasWorkspacePermission(data, profile?.id, 'manage_roles')
  const canManageMembers = isHubFounder || hasWorkspacePermission(data, profile?.id, 'manage_members')
  const actorHighestRolePosition = actorIsOwner ? Number.POSITIVE_INFINITY : Math.max(roles.filter(role => currentMember?.customRoleIds.includes(role.id)).reduce((highest, role) => Math.max(highest, role.position), 0), currentMember?.role === 'admin' ? 3_000_000 : currentMember?.role === 'contributor' ? 2_000_000 : 0)
  const search = query.trim().toLowerCase()
  const visibleMembers = useMemo(() => members.filter(member => { if (!search) return true; const roleNames = roles.filter(role => member.customRoleIds.includes(role.id)).map(role => role.name).join(' '); return `${member.displayName} ${member.username} ${member.publicUserId} ${data?.workspace.id ? workspaceRoleDisplayName(data.workspace.id, member.role) : member.role} ${roleNames}`.toLowerCase().includes(search) }), [data?.workspace.id, members, roles, search])

  function memberHierarchyRank(member: (typeof members)[number]) { if (member.role === 'owner' || member.profileId === data?.workspace.ownerId) return Number.POSITIVE_INFINITY; return Math.max(roles.filter(role => member.customRoleIds.includes(role.id)).reduce((highest, role) => Math.max(highest, role.position), 0), member.role === 'admin' ? 3_000_000 : member.role === 'contributor' ? 2_000_000 : 0) }
  function canManageMember(member: (typeof members)[number]) { if (!canManageMembers || member.profileId === profile?.id || member.role === 'owner') return false; return actorIsOwner || actorHighestRolePosition > memberHierarchyRank(member) }
  function canManageMemberRoles(member: (typeof members)[number]) { if (!canManageRoles || member.profileId === profile?.id || member.role === 'owner') return false; return actorIsOwner || actorHighestRolePosition > memberHierarchyRank(member) }
  function presenceFor(member: (typeof members)[number]) { return member.profileId === profile?.id ? effectivePresence : member.status === 'away' ? 'idle' : member.status }
  async function toggleRole(member: (typeof members)[number], roleId: string) { if (!canManageMemberRoles(member)) return; const role = roles.find(item => item.id === roleId); if (!role || (!actorIsOwner && role.position >= actorHighestRolePosition)) { pushToast('You can only assign roles below your highest role.', 'danger'); return } const roleIds = member.customRoleIds.includes(roleId) ? member.customRoleIds.filter(id => id !== roleId) : [...member.customRoleIds, roleId]; setRoleBusyId(member.id); try { await setMemberRoles(member.id, roleIds) } catch (error) { pushToast(error instanceof Error ? error.message : 'Could not update roles.', 'danger') } finally { setRoleBusyId('') } }
  async function messageMember(member: (typeof members)[number]) { if (member.profileId === profile?.id || !data?.workspace.id) return; try { const conversation = await requestDirectConversation({ targetUserId: member.profileId, sourceWorkspaceId: data.workspace.id }); window.dispatchEvent(new CustomEvent('spaces-open-direct-center', { detail: { conversationId: conversation.id } })); window.dispatchEvent(new CustomEvent('spaces-direct-activity', { detail: { key: `dm:${conversation.id}`, lastAt: Date.now(), preview: `@${member.username}` } })) } catch (error) { pushToast(error instanceof Error ? error.message : 'Could not open direct messages.', 'danger') } }
  async function reportMember(member: (typeof members)[number]) { const reason = await dialog.prompt({ title: `Report ${member.displayName}`, message: 'Tell Spaces what should be reviewed.', label: 'Reason', placeholder: 'Harassment, spam, impersonation...', confirmText: 'Continue', maxLength: 120 }); if (!reason) return; const details = await dialog.prompt({ title: 'Add details', message: 'Include any useful context.', label: 'Details', placeholder: 'What happened?', confirmText: 'Send report', maxLength: 800 }); try { await reportUser(member.profileId, reason, details ?? '') } catch (error) { pushToast(error instanceof Error ? error.message : 'Could not send report.', 'danger') } }
  async function kickMember(member: (typeof members)[number]) { if (!canManageMember(member)) return; if (!await dialog.confirm({ title: `Kick ${member.displayName}?`, message: 'They will leave this Space and need a valid invite to rejoin.', confirmText: 'Kick from Space', danger: true })) return; try { await removeMember(member.id) } catch (error) { pushToast(error instanceof Error ? error.message : 'Could not kick that member.', 'danger') } }
  async function toggleBlock(member: (typeof members)[number]) { if (!session?.token || member.profileId === profile?.id) return; const blocked = blockedUserIds.includes(member.profileId); if (!blocked && !await dialog.confirm({ title: `Block ${member.displayName}?`, message: 'Direct contact and friend requests stop until you unblock them.', confirmText: 'Block', danger: true })) return; try { if (blocked) await unblockUser(session.token, member.profileId); else await blockUser(session.token, member.profileId); pushToast(blocked ? `${member.displayName} unblocked.` : `${member.displayName} blocked.`, 'success') } catch (error) { pushToast(error instanceof Error ? error.message : 'Could not update block.', 'danger') } }
  async function muteMember(member: (typeof members)[number], minutes: number) { if (!session?.token) return; try { const center = await getDirectCenter(); const all = [...((center as typeof center & { friends?: typeof center.conversations }).friends ?? center.conversations), ...center.conversations]; const conversation = all.find(item => item.person.id === member.profileId); if (!conversation) { pushToast('Open a direct message with this person first.', 'info'); return } const response = await fetch(`${apiUrl}/v1/direct/preferences/dm/${encodeURIComponent(conversation.id)}`, { method: 'PATCH', headers: { Authorization: `Bearer ${session.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ muteMinutes: minutes }) }); if (!response.ok) throw new Error('Could not update DM mute.'); pushToast(minutes < 0 ? 'DM muted until you turn it back on.' : 'DM muted.', 'success') } catch (error) { pushToast(error instanceof Error ? error.message : 'Could not mute DM.', 'danger') } }

  function memberActions(member: (typeof members)[number]): ContextAction[] {
    const roleActions: ContextAction[] = roles.filter(role => actorIsOwner || role.position < actorHighestRolePosition).map(role => ({ id: `role:${role.id}`, label: role.name, icon: 'roles', checked: member.customRoleIds.includes(role.id), disabled: roleBusyId === member.id, onSelect: () => toggleRole(member, role.id) }))
    const blocked = blockedUserIds.includes(member.profileId)
    return [
      { id: 'profile', label: 'Profile', icon: 'user', onSelect: () => setSelectedId(member.id) },
      ...(member.profileId !== profile?.id ? [{ id: 'message', label: 'Message', icon: 'message' as const, onSelect: () => messageMember(member) }] : []),
      ...(member.profileId !== profile?.id ? [{ id: 'mention', label: 'Mention', icon: 'reply' as const, onSelect: async () => { await navigator.clipboard.writeText(`@${member.username}`); window.dispatchEvent(new CustomEvent('spaces-mention-member', { detail: `@${member.username}` })); pushToast(`@${member.username} copied.`, 'success') } }] : []),
      ...(canManageMemberRoles(member) && roleActions.length ? [{ id: 'roles', label: 'Roles', icon: 'roles' as const, separatorBefore: true, submenu: roleActions }] : []),
      ...(member.profileId !== profile?.id ? [{ id: 'mute-dm', label: 'Mute DM', icon: 'bell' as const, submenu: [
        { id: 'mute-1h', label: '1 hour', onSelect: () => muteMember(member, 60) }, { id: 'mute-8h', label: '8 hours', onSelect: () => muteMember(member, 480) }, { id: 'mute-24h', label: '24 hours', onSelect: () => muteMember(member, 1440) }, { id: 'mute-forever', label: 'Until I turn it back on', onSelect: () => muteMember(member, -1) },
      ] }] : []),
      ...(member.profileId !== profile?.id ? [{ id: 'block', label: blocked ? 'Unblock' : 'Block', icon: 'lock' as const, danger: !blocked, checked: blocked, separatorBefore: true, onSelect: () => toggleBlock(member) }, { id: 'report', label: 'Report', icon: 'shield' as const, onSelect: () => reportMember(member) }] : []),
      ...(canManageMember(member) ? [{ id: 'kick', label: 'Kick from Space', icon: 'logout' as const, danger: true, separatorBefore: true, onSelect: () => kickMember(member) }] : []),
      ...(preferences.developerMode || member.publicUserId ? [{ id: 'copy-id', label: 'Copy User ID', icon: 'copy' as const, separatorBefore: true, onSelect: async () => { await navigator.clipboard.writeText(member.publicUserId || member.profileId); pushToast('User ID copied.', 'success') } }] : []),
    ]
  }

  return <div className="members-view view-scroll page-enter members-view-v15 members-view-v18 members-view-v63 members-view-v70"><div className="content-heading people-heading-v15 people-heading-v17"><div><span className="eyebrow">COMMUNITY</span><h1>People</h1><p>Members, roles, presence, and quick actions in one place.</p><label className="people-search-v15 people-search-v17"><Icon name="search" size={15}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search people or roles..."/></label></div><span className="big-count">{visibleMembers.length === members.length ? members.length : `${visibleMembers.length}/${members.length}`}</span></div><section className="people-bubble-grid people-grid-v63 people-list-v70" aria-label="Space members">{visibleMembers.map(member => { const memberRoles = roles.filter(role => member.customRoleIds.includes(role.id)); const topRole = memberRoles[0]; const baseRoleColor = member.role === 'owner' ? data?.baseRoles?.owner?.color : data?.baseRoles?.member?.color; const roleColor = member.role === 'owner' ? baseRoleColor : (topRole?.color ?? baseRoleColor); const status = presenceFor(member); const roleLabel = topRole?.name ?? (data?.workspace.id ? workspaceRoleDisplayName(data.workspace.id, member.role) : member.role); return <article {...menu.bind(member.displayName, memberActions(member), `@${member.username}`)} className="people-bubble people-card-v63 people-row-v70" key={member.id} style={{ '--people-role-color': roleColor ?? member.profileAccent ?? '#8b6ca8' } as CSSProperties}><button
              data-member-context-v77="true"
              {...memberMenuV77.bind(member.displayName, [
                { id: 'view-profile-v77', label: 'View Profile', icon: 'user' as const, onSelect: () => setSelectedId(member.id) },
                { id: 'report-v77', label: 'Report', note: 'Open Spaces Support with this member selected', icon: 'shield' as const, onSelect: () => dispatchSupportIntakeV77({ type: 'user_report', targetUserId: member.profileId, targetUsername: member.username, targetDisplayName: member.displayName, source: 'member_context' }) },
              ], '@' + member.username)} className="people-card-main-v63" onClick={() => setSelectedId(member.id)}><span className="people-bubble-avatar profile-avatar-presence"><Avatar name={member.displayName} initials={member.initials} src={member.avatarUrl} size={40} accent={roleColor}/><i className={`presence-symbol presence-${status}`}/></span><span className="people-bubble-copy"><span className="people-name-line-v63"><strong style={roleColor ? { color: roleColor } : undefined}>{member.displayName}</strong>{member.platformRole && <em className={`people-platform-v63 platform-${member.platformRole}`}>{platformRoleLabel(member.platformRole)}</em>}</span><small>@{member.username} · {roleLabel}{preferences.developerMode && member.publicUserId ? ` · #${member.publicUserId}` : ''}</small></span><Icon name="more" size={14}/></button><div className="people-role-line-v63"><div className="people-role-chips-v63"><span className="people-role-chip-v63 base"><i style={{ background: baseRoleColor ?? undefined }}/>{data?.workspace.id ? workspaceRoleDisplayName(data.workspace.id, member.role) : member.role}</span>{memberRoles.slice(0, 3).map(role => <span className="people-role-chip-v63" key={role.id} style={{ borderColor: role.color, color: role.color }}><i style={{ background: role.color }}/>{role.name}</span>)}{memberRoles.length > 3 && <span className="people-role-more-v63">+{memberRoles.length - 3}</span>}</div></div></article>})}{!visibleMembers.length && <div className="people-empty-v15"><Icon name="members" size={22}/><strong>No people found</strong><span>Try another name or role.</span></div>}</section>      <ContextMenu menu={memberMenuV77.menu} onClose={memberMenuV77.close} />
{selectedId && <MemberProfileDrawer memberId={selectedId} onClose={() => setSelectedId('')}/>}<ContextMenu menu={menu.menu} onClose={menu.close}/></div>
}
