'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const dm=read('src/components/DirectMessagesCenter.tsx');
const shell=read('src/features/shell/AppShell.tsx');
assert.match(dm,/startSpacesDmCallV812\(/);
assert.match(dm,/onVoiceCall/);
assert.match(dm,/onVideoCall/);
assert.match(shell,/<SpacesDmCallHostV812\s*\/>/);
for(const p of ['src/features/voice/v81/SpacesPeerCallV81.ts','src/features/voice/v81/SpacesDmCallHostV812.tsx','src/features/voice/v81/SpacesVoiceApiV812.ts','src/styles/voice-v81-2.css','public/spaces-call-sounds/v81/manifest.json']) assert.ok(fs.existsSync(path.join(root,p)),p);
const icon = read('src/features/voice/v81/SpacesVoiceIconV81.tsx');
const callHost = read('src/features/voice/v81/SpacesDmCallHostV812.tsx');
const callStyles = read('src/styles/voice-v81-2.css');
assert.match(icon,/name === 'phone'/);
assert.match(icon,/name === 'phone-off'/);
assert.match(icon,/fill="currentColor"/);
assert.match(callHost,/spaces-voice-signal-v812/);
assert.match(callHost,/spaces-voice-dots-v812/);
assert.match(callStyles,/@media\(prefers-reduced-motion:reduce\)/);
const manifest=JSON.parse(read('public/spaces-call-sounds/v81/manifest.json'));
assert.equal(manifest.sounds.length,22);
console.log('PASS V81.2.1 DM header call controls, global call host, authenticated signaling client, styles, 22 sound cues');
